# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showRoutes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='way',
            name='nodes',
            field=models.ManyToManyField(related_name='nodes', through='showRoutes.Membership', to='showRoutes.Node'),
        ),
        migrations.AlterField(
            model_name='way',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='showRoutes.Tag'),
        ),
    ]
